In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
my_list = [1,2,2,3,4,5]
print(my_list)

[1, 2, 2, 3, 4, 5]


In [4]:
np.array(my_list)

array([1, 2, 2, 3, 4, 5])

In [5]:
my_matrix =[[1,2,3],[1,3,4],[1,6,8]]

In [6]:
np.array(my_matrix )

array([[1, 2, 3],
       [1, 3, 4],
       [1, 6, 8]])

In [7]:
np.arange(0,76)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75])

In [8]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(1,2)

array([[0.70627869, 0.87290255]])

In [26]:
np.random.rand(3)

array([0.02233498, 0.3430129 , 0.99155011])

In [27]:
np.random.randn(4)

array([-0.88604903, -0.76645869, -2.13573674, -0.51990315])

In [28]:
np.random.randint(1,123)

54

In [29]:
np.random.randint(1,123,2)

array([97, 61])

In [30]:
arr = np.arange(25)

In [31]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [32]:
randomarray = np.random.randint(1,25,25)

In [33]:
print(randomarray)

[21 24  1 17 16  7 11 22 24  2 11 13 22  1 22 16 10  6 21 15  5 20  3  8
 10]


In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
randomarray


array([21, 24,  1, 17, 16,  7, 11, 22, 24,  2, 11, 13, 22,  1, 22, 16, 10,
        6, 21, 15,  5, 20,  3,  8, 10])

In [36]:
randomarray.max()

24

In [37]:
randomarray.argmax()


1

In [38]:
randomarray.min()

1

In [39]:
randomarray.argmin()

2

In [42]:
arr.shape

(25,)

In [46]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
arr.reshape(1,25).shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
arr  = arr.reshape(25,1)
arr.shape

(25, 1)

In [50]:
arr.dtype


dtype('int32')