In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr[2]

2

In [6]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[4:7]

array([4, 5, 6])

In [9]:
arr[0:5] = 100


In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slicearray = arr[0:5]

In [14]:
slicearray 

array([0, 1, 2, 3, 4])

In [15]:
slicearray[:] = 99

In [16]:
slicearray

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arrcopy = arr.copy()

In [19]:
arrcopy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arrcopy[:]=90

In [21]:
arrcopy

array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Two D array


In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[1][2]

30

In [27]:
arr_2d[1,2]

30

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr_2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
boolarray = arr > 5
print(boolarray )

[False False False False False  True  True  True  True  True]


In [69]:
arr[boolarray]

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr<4]

array([1, 2, 3])

In [73]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [77]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])